### ISSUE TITLE
Landing page welcome text on desktop

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-docs#131]
**Describe the bug**
Landing page text looks janky on desktop (fine on mobile).

**To Reproduce**
1. Go to docs.telos.net
2. See screenshot

**Expected behavior**

**Screenshots**
![image](https://github.com/telosnetwork/telos-docs/assets/6848910/aad7016e-ffc6-4974-899a-1a7f6a255587)

**Desktop (please complete the following information):**
 - Browser: Chrome

**Comment by NathanHennigh** [comment]
I cant seem to replicate on Chrome.
![image](https://github.com/telosnetwork/telos-docs/assets/10350914/6ffdc4aa-02d3-4a6c-a1ae-4c1a5b750627)

**Comment by donnyquixotic** [comment]
This was unique to my browser on my machine.
