### ISSUE TITLE
Staking instructions for Native/Zero

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-docs#142]
**Describe the bug**
There isn't documentation for staking on the native side which works differently than EVM staking (for now). There are two ways to do it using our apps via the web wallet and open block explorer. There is a dead link in the current documentation

**To Reproduce**
1. Go to https://docs.telos.net/faq/#what-is-rex-and-how-does-it-work
2. Click on 'Stake Telos on an [Antelope block explorer](https://www.telos.net/ecosystem-apps-filter/block-explorer)'
3. See 404

**Expected behavior**
Should contain documentation and/or link to instructions for one or both methods, including information about 'savings' if relevant (OBE only atm), unstaking periods, etc.

**Comment by NathanHennigh** [comment]
Already included in knowledge base ports
https://docs.telos.net/knowledge-base/how-to-stake-tlos/
