### ISSUE TITLE
Add instructions and/or link for revoking allowances in the web wallet

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-docs#152]
**Description**
Revoking allowances feature is released in the web wallet, add instructions and/or a link for users. The revoke.telos.net subdomain will link to documentation and the web wallet and instruct users to revoke there.

**Tasks**

- [ ] Remove link & language referencing revoke.telos.net, this subdomain is a redundant placeholder that will link users to the web wallet and documentation 
- [ ] Add instructions/link to revoke in the web wallet

**Links**
- https://wallet.telos.net/evm/allowances
- https://docs.telos.net/knowledge-base/limit-unlimited-token-allowances/#revoke-permissions-with-metamask

**Comment by NathanHennigh** [comment]
Updated allowance revoking here https://github.com/telosnetwork/telos-docs/pull/158
