### ISSUE TITLE
Telos logo svg not rendering correctly in firefox

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-docs#160]
**Describe the bug**
See screenshot

**Screenshots**
![image](https://github.com/telosnetwork/telos-docs/assets/6848910/93a8ef29-e4b9-4544-abb8-6c6e325627c2)

**Desktop (please complete the following information):**
 - Browser: Firefox

**Additional context**
Renders correctly in Chrome, this is browser-specific. You will need a new svg or a png file. You can find the working png file used in OBE [here](https://github.com/telosnetwork/open-block-explorer/blob/master/public/chains/telos/telos_logo.png).

**Comment by NathanHennigh** [comment]
Fixed here
https://github.com/telosnetwork/telos-docs/pull/162
