### ISSUE TITLE
Update Zero linked EVM address documentation

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-docs#161]
**Describe the bug**
Outdated pages & routes are still accessible. Remove, disable and/or redirect to docs homepage. 

**To Reproduce**
1. Go to [example](https://docs.telos.net/digital-assets/zero-or-evm/evm-wallet/#link-your-native-account-to-an-evm-address)

**Expected behavior**
Users should not be able to directly navigate to outdated documentation

**Comment by NathanHennigh** [comment]
fixed here
https://github.com/telosnetwork/telos-docs/pull/164
