### ISSUE TITLE
Fix non-bp-nodes tevmc URL

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/telos-docs#178]
**Describe the bug**
https://docs.telos.network/nodes/non-bp-nodes/tevmc/
should be:
https://docs.telos.net/nodes/non-bp-nodes/tevmc/

Do a find a replace for the incorrect link and replace with correct one.

**Comment by NathanHennigh** [comment]
There was an issue with the config file, correct https://github.com/telosnetwork/telos-docs/pull/180
