### ISSUE TITLE
Add info to automatically add network(s) via Teloscan

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-docs#73]
**Description**
Currently shows the steps to manually add the network. It'd be useful to add the steps to automatically add the network(s) via Teloscan navigation. 

**Possible Solution**
Add something like this to the [Testnet Tutorial](https://docs.telos.net/quickstart/evm/testnet_tutorial) and [launch-dapp-on-tEVM](https://docs.telos.net/dapps/launch-dapp-on-tEVM) manual add instructions:
 _"You can visit [teloscan.io](https.teloscan.io) and click 'Connect' to automatically add the network to MetaMask."_

![image](https://user-images.githubusercontent.com/6848910/200059231-f0107705-843c-40b1-9788-f490c55584b6.png)

![image](https://user-images.githubusercontent.com/6848910/200061090-4dfcfb44-8c9d-4c85-ab8d-ba43807adc8c.png)

**Comment by nathanduft44** [comment]
Thanks will make sure the rest of these issues get resolved ASAP
