### ISSUE TITLE
Documentation for remix contract verification

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/telos-docs#89]
**Description**
Add documentation for deployment & verification using Remix sourcify plugin. [remix.t](https://remix.ethereum.org/)

**Screenshots**
![image](https://user-images.githubusercontent.com/6848910/207915657-7508a165-4774-46ff-904f-f50b87c11970.png)

**Comment by nathanduft44** [comment]
https://docs.telos.net/dapps/smart-contracts/verify_with_remix
